# Generated by Django 5.1.15 on 2026-02-21 22:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='pending', max_length=12)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_battle_requests', to=settings.AUTH_USER_MODEL)),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_battle_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'battles_battle_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, default='medium', max_length=10)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='waiting', max_length=12)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_challenger', to=settings.AUTH_USER_MODEL)),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_opponent', to=settings.AUTH_USER_MODEL)),
                ('problems', models.ManyToManyField(blank=True, related_name='battles', to='problems.problem')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle_wins', to=settings.AUTH_USER_MODEL)),
                ('battle_request', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle', to='battles.battlerequest')),
            ],
            options={
                'db_table': 'battles_battle',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BattleSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('language', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('wrong_answer', 'Wrong Answer'), ('time_limit', 'Time Limit Exceeded'), ('runtime_error', 'Runtime Error'), ('compile_error', 'Compile Error'), ('pending', 'Pending')], db_index=True, default='pending', max_length=20)),
                ('points_earned', models.PositiveSmallIntegerField(default=0)),
                ('error_output', models.TextField(blank=True, default='')),
                ('execution_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('memory_used_kb', models.PositiveIntegerField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='battles.battle')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_submissions', to='problems.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'battles_submission',
                'ordering': ['submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='BattleParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveIntegerField(default=0)),
                ('problems_solved', models.PositiveSmallIntegerField(default=0)),
                ('is_connected', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='battles.battle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'battles_participant',
                'unique_together': {('battle', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='battlerequest',
            index=models.Index(fields=['challenger', 'status'], name='battles_bat_challen_7dd26d_idx'),
        ),
        migrations.AddIndex(
            model_name='battlerequest',
            index=models.Index(fields=['opponent', 'status'], name='battles_bat_opponen_255395_idx'),
        ),
        migrations.AddIndex(
            model_name='battle',
            index=models.Index(fields=['status'], name='battles_bat_status_9febe4_idx'),
        ),
        migrations.AddIndex(
            model_name='battle',
            index=models.Index(fields=['challenger', 'status'], name='battles_bat_challen_7d7c50_idx'),
        ),
        migrations.AddIndex(
            model_name='battle',
            index=models.Index(fields=['opponent', 'status'], name='battles_bat_opponen_435b02_idx'),
        ),
        migrations.AddIndex(
            model_name='battlesubmission',
            index=models.Index(fields=['battle', 'user', 'problem'], name='battles_sub_battle__951a34_idx'),
        ),
        migrations.AddIndex(
            model_name='battlesubmission',
            index=models.Index(fields=['battle', 'status'], name='battles_sub_battle__1b8696_idx'),
        ),
    ]
