# Generated by Django 5.1.15 on 2026-02-21 11:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'problems_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(help_text='Problem statement (supports HTML).')),
                ('input_format', models.TextField(blank=True, default='')),
                ('output_format', models.TextField(blank=True, default='')),
                ('constraints', models.TextField(blank=True, default='')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, default='easy', max_length=10)),
                ('time_limit_ms', models.PositiveIntegerField(default=2000, help_text='Time limit in milliseconds.')),
                ('memory_limit_mb', models.PositiveIntegerField(default=256, help_text='Memory limit in MB.')),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('total_submissions', models.PositiveIntegerField(default=0)),
                ('accepted_submissions', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='problems.category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_problems', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'problems_problem',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_data', models.TextField(help_text='Input for the test case.')),
                ('expected_output', models.TextField(help_text='Expected output.')),
                ('is_sample', models.BooleanField(default=False, help_text='Visible to users as a sample.')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='problems.problem')),
            ],
            options={
                'db_table': 'problems_testcase',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['difficulty', 'is_published'], name='idx_problem_diff_pub'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['slug'], name='idx_problem_slug'),
        ),
    ]
