# Generated by Django 5.1.15 on 2026-02-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="join_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Unique code for joining private contests.",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="contest",
            name="visibility",
            field=models.CharField(
                choices=[("public", "Public"), ("private", "Private")],
                db_index=True,
                default="public",
                max_length=10,
            ),
        ),
    ]
