# Generated by Django 5.1.15 on 2026-02-21 14:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizerProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "org_name",
                    models.CharField(
                        help_text="Name of the organization.", max_length=200
                    ),
                ),
                (
                    "org_type",
                    models.CharField(
                        choices=[
                            ("college", "College"),
                            ("university", "University"),
                            ("company", "Company"),
                            ("community", "Community"),
                            ("other", "Other"),
                        ],
                        default="college",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("website", models.URLField(blank=True, default="")),
                ("logo_url", models.URLField(blank=True, default="", max_length=500)),
                ("location", models.CharField(blank=True, default="", max_length=200)),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the organization has been verified by site admins.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organizer Profile",
                "verbose_name_plural": "Organizer Profiles",
                "db_table": "organizer_profile",
            },
        ),
    ]
