# Generated by Django 5.1.15 on 2026-02-21 11:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.PositiveIntegerField(db_index=True, default=0)),
                ('score', models.IntegerField(default=0)),
                ('penalty', models.IntegerField(default=0)),
                ('problems_solved', models.PositiveIntegerField(default=0)),
                ('last_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='contests.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leaderboard_entry',
                'ordering': ['rank'],
                'indexes': [models.Index(fields=['contest', 'rank'], name='idx_lb_contest_rank')],
                'unique_together': {('contest', 'user')},
            },
        ),
    ]
