# Generated by Django 5.1.15 on 2026-02-21 11:06

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the user.', primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, help_text="User's email address (used for login).", max_length=255, unique=True)),
                ('username', models.CharField(db_index=True, help_text='Unique username (3-30 alphanumeric/underscore characters).', max_length=30, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], db_index=True, default='user', help_text='User role for access control.', max_length=10)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('avatar_url', models.URLField(blank=True, default='', max_length=500)),
                ('bio', models.TextField(blank=True, default='', max_length=500)),
                ('problems_solved', models.PositiveIntegerField(default=0)),
                ('contests_participated', models.PositiveIntegerField(default=0)),
                ('rating', models.IntegerField(db_index=True, default=0)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'accounts_user',
                'ordering': ['-date_joined'],
                'indexes': [models.Index(fields=['email'], name='idx_user_email'), models.Index(fields=['username'], name='idx_user_username'), models.Index(fields=['rating'], name='idx_user_rating'), models.Index(fields=['role'], name='idx_user_role')],
            },
        ),
    ]
