# Generated by Django 5.1.15 on 2026-02-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("user", "User"),
                    ("organizer", "Organizer"),
                ],
                db_index=True,
                default="user",
                help_text="User role for access control.",
                max_length=10,
            ),
        ),
    ]
