# Generated by Django 5.1.15 on 2026-02-21 11:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0001_initial'),
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('python', 'Python'), ('cpp', 'C++'), ('java', 'Java'), ('javascript', 'JavaScript')], max_length=15)),
                ('code', models.TextField(help_text="User's submitted source code.")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('accepted', 'Accepted'), ('wrong_answer', 'Wrong Answer'), ('time_limit', 'Time Limit Exceeded'), ('memory_limit', 'Memory Limit Exceeded'), ('runtime_error', 'Runtime Error'), ('compilation_error', 'Compilation Error'), ('internal_error', 'Internal Error')], db_index=True, default='pending', max_length=20)),
                ('execution_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('memory_used_kb', models.PositiveIntegerField(blank=True, null=True)),
                ('test_cases_passed', models.PositiveIntegerField(default=0)),
                ('total_test_cases', models.PositiveIntegerField(default=0)),
                ('error_output', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('judged_at', models.DateTimeField(blank=True, null=True)),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='contests.contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problems.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'submissions_submission',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['user', 'problem'], name='idx_sub_user_problem'), models.Index(fields=['status', 'submitted_at'], name='idx_sub_status_time'), models.Index(fields=['contest', 'user'], name='idx_sub_contest_user')],
            },
        ),
    ]
